 name: Azure Static Web Apps CI/CD

 on:
  push:
    branches:
      - main

 jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Azure CLI and deploy
        uses: azure/cli@v1
        with:
          inlineScript: |
            az staticwebapp upload \
              --name YOUR_STATIC_WEB_APP_NAME \
              --resource-group YOUR_RESOURCE_GROUP_NAME \
              --source. \
              --api-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
